collections:
  experiments:
    output: true
  notes:
    output: true
    permalink: /notes/:name/
  thoughts:
    output: true
    permalink: /thoughts/:name/

permalink: /:year/:month/:day/:title/

#baseurl: /website

plugins:
  - jekyll-feed

excerpt_separator: <!-- more -->

defaults:
  - scope:
      path: "_notes"
      type: "notes"
    values:
      layout: "article-writing"
  - scope:
      path: "_thoughts"
      type: "thoughts"
    values:
      layout: "article-writing"